import type { Metadata } from "next";
import { Inter, Cedarville_Cursive} from "next/font/google";
import "./globals.css";
import HomePage from "@/Components/HomePage";
import About from "@/Components/About";
import Work from "@/Components/Work";

const inter = Inter({ subsets: ["latin"] });
const Cedarville_cursive = Cedarville_Cursive({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-Cedarville-cursive',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Cedarville_cursive.variable} scrollbar-hide`}>
        <div className="max-w-[100%] h-screen overflow-y-scroll overflow-x-hidden scrollbar-hide">
          <HomePage/>
          <About/>
          <Work/>
        </div>
      </body>
    </html>
  );
}
